apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-world-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-world-app
  policy:
    semver:
      range: 5.0.x
