apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
spec:
  targetNamespace: elk
  interval: 24h
  timeout: 10m
  releaseName: fluent-bit
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      chart: fluent-bit
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            Host elk-elasticsearch
            Port 9200
            Logstash_Format On
            Retry_Limit False
            tls On
            tls.verify Off
            HTTP_User admin
            HTTP_Passwd admin
            Suppress_Type_Name On
    
        [OUTPUT]
            Name es
            Match host.*
            Host elk-elasticsearch
            Port 9200
            Logstash_Format On
            Logstash_Prefix node
            Retry_Limit False
            tls On
            tls.verify Off
            HTTP_User admin
            HTTP_Passwd admin
            Suppress_Type_Name On
